// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax.messages;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_CameraViewArguments_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_CameraViewArguments_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_CameraSelector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_CameraSelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Camera_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_Camera_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_CameraInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_CameraInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_CameraControl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_CameraControl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_TorchStateArguments_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_TorchStateArguments_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\010messages\"U\n\023CameraView" +
      "Arguments\022\025\n\rcontroller_id\030\001 \001(\t\022\'\n\nscal" +
      "e_type\030\002 \001(\0162\023.messages.ScaleType\"8\n\016Cam" +
      "eraSelector\022&\n\006facing\030\001 \001(\0162\026.messages.C" +
      "ameraFacing\"d\n\006Camera\022)\n\013camera_info\030\001 \001" +
      "(\0132\024.messages.CameraInfo\022/\n\016camera_contr" +
      "ol\030\002 \001(\0132\027.messages.CameraControl\"1\n\nCam" +
      "eraInfo\022\n\n\002id\030\001 \001(\t\022\027\n\017torch_available\030\002" +
      " \001(\010\"\033\n\rCameraControl\022\n\n\002id\030\001 \001(\t\"0\n\023Tor" +
      "chStateArguments\022\n\n\002id\030\001 \001(\t\022\r\n\005state\030\002 " +
      "\001(\010*\250\001\n\tScaleType\022\031\n\025SCALE_TYPE_FILL_STA" +
      "RT\020\000\022\032\n\026SCALE_TYPE_FILL_CENTER\020\001\022\027\n\023SCAL" +
      "E_TYPE_FILL_END\020\002\022\030\n\024SCALE_TYPE_FIT_STAR" +
      "T\020\003\022\031\n\025SCALE_TYPE_FIT_CENTER\020\004\022\026\n\022SCALE_" +
      "TYPE_FIT_END\020\005*?\n\014CameraFacing\022\026\n\022CAMERA" +
      "_FACING_BACK\020\000\022\027\n\023CAMERA_FACING_FRONT\020\001B" +
      "$\n dev.yanshouwang.camerax.messagesP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_messages_CameraViewArguments_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_CameraViewArguments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_CameraViewArguments_descriptor,
        new java.lang.String[] { "ControllerId", "ScaleType", });
    internal_static_messages_CameraSelector_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messages_CameraSelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_CameraSelector_descriptor,
        new java.lang.String[] { "Facing", });
    internal_static_messages_Camera_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_messages_Camera_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_Camera_descriptor,
        new java.lang.String[] { "CameraInfo", "CameraControl", });
    internal_static_messages_CameraInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_messages_CameraInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_CameraInfo_descriptor,
        new java.lang.String[] { "Id", "TorchAvailable", });
    internal_static_messages_CameraControl_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_messages_CameraControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_CameraControl_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_messages_TorchStateArguments_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_messages_TorchStateArguments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_TorchStateArguments_descriptor,
        new java.lang.String[] { "Id", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
