//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax.messages;

@kotlin.jvm.JvmName("-initializecameraControllerCaptureToMemoryCommandArguments")
inline fun cameraControllerCaptureToMemoryCommandArguments(block: dev.yanshouwang.camerax.messages.CameraControllerCaptureToMemoryCommandArgumentsKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.messages.Messages.CameraControllerCaptureToMemoryCommandArguments =
  dev.yanshouwang.camerax.messages.CameraControllerCaptureToMemoryCommandArgumentsKt.Dsl._create(dev.yanshouwang.camerax.messages.Messages.CameraControllerCaptureToMemoryCommandArguments.newBuilder()).apply { block() }._build()
object CameraControllerCaptureToMemoryCommandArgumentsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: dev.yanshouwang.camerax.messages.Messages.CameraControllerCaptureToMemoryCommandArguments.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.messages.Messages.CameraControllerCaptureToMemoryCommandArguments.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.messages.Messages.CameraControllerCaptureToMemoryCommandArguments = _builder.build()

    /**
     * <code>.messages.CameraSelector selector = 1;</code>
     */
    var selector: dev.yanshouwang.camerax.messages.Messages.CameraSelector
      @JvmName("getSelector")
      get() = _builder.getSelector()
      @JvmName("setSelector")
      set(value) {
        _builder.setSelector(value)
      }
    /**
     * <code>.messages.CameraSelector selector = 1;</code>
     */
    fun clearSelector() {
      _builder.clearSelector()
    }
    /**
     * <code>.messages.CameraSelector selector = 1;</code>
     * @return Whether the selector field is set.
     */
    fun hasSelector(): kotlin.Boolean {
      return _builder.hasSelector()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.messages.Messages.CameraControllerCaptureToMemoryCommandArguments.copy(block: dev.yanshouwang.camerax.messages.CameraControllerCaptureToMemoryCommandArgumentsKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.messages.Messages.CameraControllerCaptureToMemoryCommandArguments =
  dev.yanshouwang.camerax.messages.CameraControllerCaptureToMemoryCommandArgumentsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val dev.yanshouwang.camerax.messages.Messages.CameraControllerCaptureToMemoryCommandArgumentsOrBuilder.selectorOrNull: dev.yanshouwang.camerax.messages.Messages.CameraSelector?
  get() = if (hasSelector()) getSelector() else null

