// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:ffi' as ffi;
import 'dart:isolate' show ReceivePort;

import 'package:jni/internal_helpers_for_jnigen.dart';
import 'package:jni/jni.dart' as jni;

/// from: androidx.camera.core.TorchState$State
class TorchState_State extends jni.JObject {
  @override
  late final jni.JObjType<TorchState_State> $type = type;

  TorchState_State.fromReference(
    jni.JReference reference,
  ) : super.fromReference(reference);

  static final _class =
      jni.JClass.forName(r'androidx/camera/core/TorchState$State');

  /// The type which includes information such as the signature of this class.
  static const type = $TorchState_StateType();

  /// Maps a specific port to the implemented interface.
  static final Map<int, $TorchState_StateImpl> _$impls = {};
  ReceivePort? _$p;

  static jni.JObjectPtr _$invoke(
    int port,
    jni.JObjectPtr descriptor,
    jni.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      $MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final ffi.Pointer<
          ffi.NativeFunction<
              jni.JObjectPtr Function(
                  ffi.Uint64, jni.JObjectPtr, jni.JObjectPtr)>>
      _$invokePointer = ffi.Pointer.fromFunction(_$invoke);

  static ffi.Pointer<ffi.Void> _$invokeMethod(
    int $p,
    $MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
    } catch (e) {
      return ProtectedJniExtensions.newDartException(e);
    }
    return jni.nullptr;
  }

  factory TorchState_State.implement(
    $TorchState_StateImpl $impl,
  ) {
    final $p = ReceivePort();
    final $x = TorchState_State.fromReference(
      ProtectedJniExtensions.newPortProxy(
        r'androidx.camera.core.TorchState$State',
        $p,
        _$invokePointer,
      ),
    ).._$p = $p;
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
    $p.listen(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = $MethodInvocation.fromMessage($m as List<dynamic>);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      ProtectedJniExtensions.returnResult($i.result, $r);
    });
    return $x;
  }
}

abstract interface class $TorchState_StateImpl {
  factory $TorchState_StateImpl() = _$TorchState_StateImpl;
}

class _$TorchState_StateImpl implements $TorchState_StateImpl {
  _$TorchState_StateImpl();
}

final class $TorchState_StateType extends jni.JObjType<TorchState_State> {
  const $TorchState_StateType();

  @override
  String get signature => r'Landroidx/camera/core/TorchState$State;';

  @override
  TorchState_State fromReference(jni.JReference reference) =>
      TorchState_State.fromReference(reference);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($TorchState_StateType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($TorchState_StateType) &&
        other is $TorchState_StateType;
  }
}

/// from: androidx.camera.core.TorchState
class TorchState extends jni.JObject {
  @override
  late final jni.JObjType<TorchState> $type = type;

  TorchState.fromReference(
    jni.JReference reference,
  ) : super.fromReference(reference);

  static final _class = jni.JClass.forName(r'androidx/camera/core/TorchState');

  /// The type which includes information such as the signature of this class.
  static const type = $TorchStateType();

  /// from: static public final int OFF
  static const OFF = 0;

  /// from: static public final int ON
  static const ON = 1;
}

final class $TorchStateType extends jni.JObjType<TorchState> {
  const $TorchStateType();

  @override
  String get signature => r'Landroidx/camera/core/TorchState;';

  @override
  TorchState fromReference(jni.JReference reference) =>
      TorchState.fromReference(reference);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($TorchStateType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($TorchStateType) && other is $TorchStateType;
  }
}
