name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - camerax_platform_interface
  - camerax_android
  - camerax_android/example
  - camerax_ios
  - camerax_ios/example
  - camerax_linux
  - camerax_linux/example
  - camerax
  - camerax/example
