// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:ffi' as ffi;
import 'dart:isolate' show ReceivePort;

import 'package:jni/internal_helpers_for_jnigen.dart';
import 'package:jni/jni.dart' as jni;

/// from: com.google.android.gms.tasks.OnCanceledListener
class OnCanceledListener extends jni.JObject {
  @override
  late final jni.JObjType<OnCanceledListener> $type = type;

  OnCanceledListener.fromReference(
    jni.JReference reference,
  ) : super.fromReference(reference);

  static final _class =
      jni.JClass.forName(r'com/google/android/gms/tasks/OnCanceledListener');

  /// The type which includes information such as the signature of this class.
  static const type = $OnCanceledListenerType();
  static final _id_onCanceled = _class.instanceMethodId(
    r'onCanceled',
    r'()V',
  );

  static final _onCanceled = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JThrowablePtr Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: public abstract void onCanceled()
  void onCanceled() {
    _onCanceled(reference.pointer, _id_onCanceled as jni.JMethodIDPtr).check();
  }

  /// Maps a specific port to the implemented interface.
  static final Map<int, $OnCanceledListenerImpl> _$impls = {};
  ReceivePort? _$p;

  static jni.JObjectPtr _$invoke(
    int port,
    jni.JObjectPtr descriptor,
    jni.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      $MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final ffi.Pointer<
          ffi.NativeFunction<
              jni.JObjectPtr Function(
                  ffi.Uint64, jni.JObjectPtr, jni.JObjectPtr)>>
      _$invokePointer = ffi.Pointer.fromFunction(_$invoke);

  static ffi.Pointer<ffi.Void> _$invokeMethod(
    int $p,
    $MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onCanceled()V') {
        _$impls[$p]!.onCanceled();
        return jni.nullptr;
      }
    } catch (e) {
      return ProtectedJniExtensions.newDartException(e);
    }
    return jni.nullptr;
  }

  factory OnCanceledListener.implement(
    $OnCanceledListenerImpl $impl,
  ) {
    final $p = ReceivePort();
    final $x = OnCanceledListener.fromReference(
      ProtectedJniExtensions.newPortProxy(
        r'com.google.android.gms.tasks.OnCanceledListener',
        $p,
        _$invokePointer,
      ),
    ).._$p = $p;
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
    $p.listen(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = $MethodInvocation.fromMessage($m as List<dynamic>);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      ProtectedJniExtensions.returnResult($i.result, $r);
    });
    return $x;
  }
}

abstract interface class $OnCanceledListenerImpl {
  factory $OnCanceledListenerImpl({
    required void Function() onCanceled,
  }) = _$OnCanceledListenerImpl;

  void onCanceled();
}

class _$OnCanceledListenerImpl implements $OnCanceledListenerImpl {
  _$OnCanceledListenerImpl({
    required void Function() onCanceled,
  }) : _onCanceled = onCanceled;

  final void Function() _onCanceled;

  void onCanceled() {
    return _onCanceled();
  }
}

final class $OnCanceledListenerType extends jni.JObjType<OnCanceledListener> {
  const $OnCanceledListenerType();

  @override
  String get signature => r'Lcom/google/android/gms/tasks/OnCanceledListener;';

  @override
  OnCanceledListener fromReference(jni.JReference reference) =>
      OnCanceledListener.fromReference(reference);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($OnCanceledListenerType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($OnCanceledListenerType) &&
        other is $OnCanceledListenerType;
  }
}
