name: camerax_linux
description: 'Linux implementation of the camerax plugin.'
version: 0.0.1
repository: https://github.com/yanshouwang/camerax
issue_tracker: https://github.com/yanshouwang/camerax/issues
topics:
  - camera
  - camerax

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camerax_platform_interface:
    path: ../camerax_platform_interface
  hybrid_v4l2:
    path: ../../hybrid_sdk/hybrid_v4l2
  hybrid_yuv:
    path: ../../hybrid_sdk/hybrid_yuv
  ffi: ^2.1.3
  logging: ^1.3.0
  hybrid_logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^14.0.1

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: CameraXLinuxPlugin
        dartPluginClass: CameraXLinuxPlugin
      elinux:
        pluginClass: CameraXLinuxPlugin
        dartPluginClass: CameraXLinuxPlugin
