// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `dev.hebei.camerax_android.core.AspectRatio`
class AspectRatio extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<AspectRatio> $type;

  @jni$_.internal
  AspectRatio.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      jni$_.JClass.forName(r'dev/hebei/camerax_android/core/AspectRatio');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $AspectRatio$NullableType();
  static const type = $AspectRatio$Type();
  static final _id_RATIO_DEFAULT = _class.staticFieldId(
    r'RATIO_DEFAULT',
    r'Ldev/hebei/camerax_android/core/AspectRatio;',
  );

  /// from: `static public final dev.hebei.camerax_android.core.AspectRatio RATIO_DEFAULT`
  /// The returned object must be released after use, by calling the [release] method.
  static AspectRatio? get RATIO_DEFAULT =>
      _id_RATIO_DEFAULT.get(_class, const $AspectRatio$NullableType());

  static final _id_RATIO_4_3 = _class.staticFieldId(
    r'RATIO_4_3',
    r'Ldev/hebei/camerax_android/core/AspectRatio;',
  );

  /// from: `static public final dev.hebei.camerax_android.core.AspectRatio RATIO_4_3`
  /// The returned object must be released after use, by calling the [release] method.
  static AspectRatio? get RATIO_4_3 =>
      _id_RATIO_4_3.get(_class, const $AspectRatio$NullableType());

  static final _id_RATIO_16_9 = _class.staticFieldId(
    r'RATIO_16_9',
    r'Ldev/hebei/camerax_android/core/AspectRatio;',
  );

  /// from: `static public final dev.hebei.camerax_android.core.AspectRatio RATIO_16_9`
  /// The returned object must be released after use, by calling the [release] method.
  static AspectRatio? get RATIO_16_9 =>
      _id_RATIO_16_9.get(_class, const $AspectRatio$NullableType());

  static final _id_values = _class.staticMethodId(
    r'values',
    r'()[Ldev/hebei/camerax_android/core/AspectRatio;',
  );

  static final _values = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `static public dev.hebei.camerax_android.core.AspectRatio[] values()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<AspectRatio?>? values() {
    return _values(_class.reference.pointer, _id_values as jni$_.JMethodIDPtr)
        .object<jni$_.JArray<AspectRatio?>?>(
            const jni$_.JArrayNullableType<AspectRatio?>(
                $AspectRatio$NullableType()));
  }

  static final _id_valueOf = _class.staticMethodId(
    r'valueOf',
    r'(Ljava/lang/String;)Ldev/hebei/camerax_android/core/AspectRatio;',
  );

  static final _valueOf = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `static public dev.hebei.camerax_android.core.AspectRatio valueOf(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  static AspectRatio? valueOf(
    jni$_.JString? string,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _valueOf(_class.reference.pointer, _id_valueOf as jni$_.JMethodIDPtr,
            _$string.pointer)
        .object<AspectRatio?>(const $AspectRatio$NullableType());
  }
}

final class $AspectRatio$NullableType extends jni$_.JObjType<AspectRatio?> {
  @jni$_.internal
  const $AspectRatio$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/hebei/camerax_android/core/AspectRatio;';

  @jni$_.internal
  @core$_.override
  AspectRatio? fromReference(jni$_.JReference reference) => reference.isNull
      ? null
      : AspectRatio.fromReference(
          reference,
        );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<AspectRatio?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($AspectRatio$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($AspectRatio$NullableType) &&
        other is $AspectRatio$NullableType;
  }
}

final class $AspectRatio$Type extends jni$_.JObjType<AspectRatio> {
  @jni$_.internal
  const $AspectRatio$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/hebei/camerax_android/core/AspectRatio;';

  @jni$_.internal
  @core$_.override
  AspectRatio fromReference(jni$_.JReference reference) =>
      AspectRatio.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<AspectRatio?> get nullableType =>
      const $AspectRatio$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($AspectRatio$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($AspectRatio$Type) &&
        other is $AspectRatio$Type;
  }
}
