// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax.messages;

/**
 * Protobuf type {@code messages.MLMetadata}
 */
public final class MLMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:messages.MLMetadata)
    MLMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MLMetadata.newBuilder() to construct.
  private MLMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MLMetadata() {
    corners_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MLMetadata();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MLMetadata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              corners_ = new java.util.ArrayList<dev.yanshouwang.camerax.messages.Offset>();
              mutable_bitField0_ |= 0x00000001;
            }
            corners_.add(
                input.readMessage(dev.yanshouwang.camerax.messages.Offset.parser(), extensionRegistry));
            break;
          }
          case 18: {
            dev.yanshouwang.camerax.messages.Barcode.Builder subBuilder = null;
            if (metadataCase_ == 2) {
              subBuilder = ((dev.yanshouwang.camerax.messages.Barcode) metadata_).toBuilder();
            }
            metadata_ =
                input.readMessage(dev.yanshouwang.camerax.messages.Barcode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((dev.yanshouwang.camerax.messages.Barcode) metadata_);
              metadata_ = subBuilder.buildPartial();
            }
            metadataCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        corners_ = java.util.Collections.unmodifiableList(corners_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.yanshouwang.camerax.messages.Messages.internal_static_messages_MLMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.yanshouwang.camerax.messages.Messages.internal_static_messages_MLMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.yanshouwang.camerax.messages.MLMetadata.class, dev.yanshouwang.camerax.messages.MLMetadata.Builder.class);
  }

  private int metadataCase_ = 0;
  private java.lang.Object metadata_;
  public enum MetadataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    BARCODE(2),
    METADATA_NOT_SET(0);
    private final int value;
    private MetadataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MetadataCase valueOf(int value) {
      return forNumber(value);
    }

    public static MetadataCase forNumber(int value) {
      switch (value) {
        case 2: return BARCODE;
        case 0: return METADATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MetadataCase
  getMetadataCase() {
    return MetadataCase.forNumber(
        metadataCase_);
  }

  public static final int CORNERS_FIELD_NUMBER = 1;
  private java.util.List<dev.yanshouwang.camerax.messages.Offset> corners_;
  /**
   * <code>repeated .messages.Offset corners = 1;</code>
   */
  @java.lang.Override
  public java.util.List<dev.yanshouwang.camerax.messages.Offset> getCornersList() {
    return corners_;
  }
  /**
   * <code>repeated .messages.Offset corners = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dev.yanshouwang.camerax.messages.OffsetOrBuilder> 
      getCornersOrBuilderList() {
    return corners_;
  }
  /**
   * <code>repeated .messages.Offset corners = 1;</code>
   */
  @java.lang.Override
  public int getCornersCount() {
    return corners_.size();
  }
  /**
   * <code>repeated .messages.Offset corners = 1;</code>
   */
  @java.lang.Override
  public dev.yanshouwang.camerax.messages.Offset getCorners(int index) {
    return corners_.get(index);
  }
  /**
   * <code>repeated .messages.Offset corners = 1;</code>
   */
  @java.lang.Override
  public dev.yanshouwang.camerax.messages.OffsetOrBuilder getCornersOrBuilder(
      int index) {
    return corners_.get(index);
  }

  public static final int BARCODE_FIELD_NUMBER = 2;
  /**
   * <code>.messages.Barcode barcode = 2;</code>
   * @return Whether the barcode field is set.
   */
  @java.lang.Override
  public boolean hasBarcode() {
    return metadataCase_ == 2;
  }
  /**
   * <code>.messages.Barcode barcode = 2;</code>
   * @return The barcode.
   */
  @java.lang.Override
  public dev.yanshouwang.camerax.messages.Barcode getBarcode() {
    if (metadataCase_ == 2) {
       return (dev.yanshouwang.camerax.messages.Barcode) metadata_;
    }
    return dev.yanshouwang.camerax.messages.Barcode.getDefaultInstance();
  }
  /**
   * <code>.messages.Barcode barcode = 2;</code>
   */
  @java.lang.Override
  public dev.yanshouwang.camerax.messages.BarcodeOrBuilder getBarcodeOrBuilder() {
    if (metadataCase_ == 2) {
       return (dev.yanshouwang.camerax.messages.Barcode) metadata_;
    }
    return dev.yanshouwang.camerax.messages.Barcode.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < corners_.size(); i++) {
      output.writeMessage(1, corners_.get(i));
    }
    if (metadataCase_ == 2) {
      output.writeMessage(2, (dev.yanshouwang.camerax.messages.Barcode) metadata_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < corners_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, corners_.get(i));
    }
    if (metadataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (dev.yanshouwang.camerax.messages.Barcode) metadata_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.yanshouwang.camerax.messages.MLMetadata)) {
      return super.equals(obj);
    }
    dev.yanshouwang.camerax.messages.MLMetadata other = (dev.yanshouwang.camerax.messages.MLMetadata) obj;

    if (!getCornersList()
        .equals(other.getCornersList())) return false;
    if (!getMetadataCase().equals(other.getMetadataCase())) return false;
    switch (metadataCase_) {
      case 2:
        if (!getBarcode()
            .equals(other.getBarcode())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCornersCount() > 0) {
      hash = (37 * hash) + CORNERS_FIELD_NUMBER;
      hash = (53 * hash) + getCornersList().hashCode();
    }
    switch (metadataCase_) {
      case 2:
        hash = (37 * hash) + BARCODE_FIELD_NUMBER;
        hash = (53 * hash) + getBarcode().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.yanshouwang.camerax.messages.MLMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.yanshouwang.camerax.messages.MLMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code messages.MLMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:messages.MLMetadata)
      dev.yanshouwang.camerax.messages.MLMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.yanshouwang.camerax.messages.Messages.internal_static_messages_MLMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.yanshouwang.camerax.messages.Messages.internal_static_messages_MLMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.yanshouwang.camerax.messages.MLMetadata.class, dev.yanshouwang.camerax.messages.MLMetadata.Builder.class);
    }

    // Construct using dev.yanshouwang.camerax.messages.MLMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCornersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (cornersBuilder_ == null) {
        corners_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        cornersBuilder_.clear();
      }
      metadataCase_ = 0;
      metadata_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.yanshouwang.camerax.messages.Messages.internal_static_messages_MLMetadata_descriptor;
    }

    @java.lang.Override
    public dev.yanshouwang.camerax.messages.MLMetadata getDefaultInstanceForType() {
      return dev.yanshouwang.camerax.messages.MLMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public dev.yanshouwang.camerax.messages.MLMetadata build() {
      dev.yanshouwang.camerax.messages.MLMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.yanshouwang.camerax.messages.MLMetadata buildPartial() {
      dev.yanshouwang.camerax.messages.MLMetadata result = new dev.yanshouwang.camerax.messages.MLMetadata(this);
      int from_bitField0_ = bitField0_;
      if (cornersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          corners_ = java.util.Collections.unmodifiableList(corners_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.corners_ = corners_;
      } else {
        result.corners_ = cornersBuilder_.build();
      }
      if (metadataCase_ == 2) {
        if (barcodeBuilder_ == null) {
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = barcodeBuilder_.build();
        }
      }
      result.metadataCase_ = metadataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.yanshouwang.camerax.messages.MLMetadata) {
        return mergeFrom((dev.yanshouwang.camerax.messages.MLMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.yanshouwang.camerax.messages.MLMetadata other) {
      if (other == dev.yanshouwang.camerax.messages.MLMetadata.getDefaultInstance()) return this;
      if (cornersBuilder_ == null) {
        if (!other.corners_.isEmpty()) {
          if (corners_.isEmpty()) {
            corners_ = other.corners_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCornersIsMutable();
            corners_.addAll(other.corners_);
          }
          onChanged();
        }
      } else {
        if (!other.corners_.isEmpty()) {
          if (cornersBuilder_.isEmpty()) {
            cornersBuilder_.dispose();
            cornersBuilder_ = null;
            corners_ = other.corners_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cornersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCornersFieldBuilder() : null;
          } else {
            cornersBuilder_.addAllMessages(other.corners_);
          }
        }
      }
      switch (other.getMetadataCase()) {
        case BARCODE: {
          mergeBarcode(other.getBarcode());
          break;
        }
        case METADATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dev.yanshouwang.camerax.messages.MLMetadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dev.yanshouwang.camerax.messages.MLMetadata) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int metadataCase_ = 0;
    private java.lang.Object metadata_;
    public MetadataCase
        getMetadataCase() {
      return MetadataCase.forNumber(
          metadataCase_);
    }

    public Builder clearMetadata() {
      metadataCase_ = 0;
      metadata_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.util.List<dev.yanshouwang.camerax.messages.Offset> corners_ =
      java.util.Collections.emptyList();
    private void ensureCornersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        corners_ = new java.util.ArrayList<dev.yanshouwang.camerax.messages.Offset>(corners_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dev.yanshouwang.camerax.messages.Offset, dev.yanshouwang.camerax.messages.Offset.Builder, dev.yanshouwang.camerax.messages.OffsetOrBuilder> cornersBuilder_;

    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public java.util.List<dev.yanshouwang.camerax.messages.Offset> getCornersList() {
      if (cornersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(corners_);
      } else {
        return cornersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public int getCornersCount() {
      if (cornersBuilder_ == null) {
        return corners_.size();
      } else {
        return cornersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public dev.yanshouwang.camerax.messages.Offset getCorners(int index) {
      if (cornersBuilder_ == null) {
        return corners_.get(index);
      } else {
        return cornersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public Builder setCorners(
        int index, dev.yanshouwang.camerax.messages.Offset value) {
      if (cornersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCornersIsMutable();
        corners_.set(index, value);
        onChanged();
      } else {
        cornersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public Builder setCorners(
        int index, dev.yanshouwang.camerax.messages.Offset.Builder builderForValue) {
      if (cornersBuilder_ == null) {
        ensureCornersIsMutable();
        corners_.set(index, builderForValue.build());
        onChanged();
      } else {
        cornersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public Builder addCorners(dev.yanshouwang.camerax.messages.Offset value) {
      if (cornersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCornersIsMutable();
        corners_.add(value);
        onChanged();
      } else {
        cornersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public Builder addCorners(
        int index, dev.yanshouwang.camerax.messages.Offset value) {
      if (cornersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCornersIsMutable();
        corners_.add(index, value);
        onChanged();
      } else {
        cornersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public Builder addCorners(
        dev.yanshouwang.camerax.messages.Offset.Builder builderForValue) {
      if (cornersBuilder_ == null) {
        ensureCornersIsMutable();
        corners_.add(builderForValue.build());
        onChanged();
      } else {
        cornersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public Builder addCorners(
        int index, dev.yanshouwang.camerax.messages.Offset.Builder builderForValue) {
      if (cornersBuilder_ == null) {
        ensureCornersIsMutable();
        corners_.add(index, builderForValue.build());
        onChanged();
      } else {
        cornersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public Builder addAllCorners(
        java.lang.Iterable<? extends dev.yanshouwang.camerax.messages.Offset> values) {
      if (cornersBuilder_ == null) {
        ensureCornersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, corners_);
        onChanged();
      } else {
        cornersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public Builder clearCorners() {
      if (cornersBuilder_ == null) {
        corners_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cornersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public Builder removeCorners(int index) {
      if (cornersBuilder_ == null) {
        ensureCornersIsMutable();
        corners_.remove(index);
        onChanged();
      } else {
        cornersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public dev.yanshouwang.camerax.messages.Offset.Builder getCornersBuilder(
        int index) {
      return getCornersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public dev.yanshouwang.camerax.messages.OffsetOrBuilder getCornersOrBuilder(
        int index) {
      if (cornersBuilder_ == null) {
        return corners_.get(index);  } else {
        return cornersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public java.util.List<? extends dev.yanshouwang.camerax.messages.OffsetOrBuilder> 
         getCornersOrBuilderList() {
      if (cornersBuilder_ != null) {
        return cornersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(corners_);
      }
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public dev.yanshouwang.camerax.messages.Offset.Builder addCornersBuilder() {
      return getCornersFieldBuilder().addBuilder(
          dev.yanshouwang.camerax.messages.Offset.getDefaultInstance());
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public dev.yanshouwang.camerax.messages.Offset.Builder addCornersBuilder(
        int index) {
      return getCornersFieldBuilder().addBuilder(
          index, dev.yanshouwang.camerax.messages.Offset.getDefaultInstance());
    }
    /**
     * <code>repeated .messages.Offset corners = 1;</code>
     */
    public java.util.List<dev.yanshouwang.camerax.messages.Offset.Builder> 
         getCornersBuilderList() {
      return getCornersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dev.yanshouwang.camerax.messages.Offset, dev.yanshouwang.camerax.messages.Offset.Builder, dev.yanshouwang.camerax.messages.OffsetOrBuilder> 
        getCornersFieldBuilder() {
      if (cornersBuilder_ == null) {
        cornersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dev.yanshouwang.camerax.messages.Offset, dev.yanshouwang.camerax.messages.Offset.Builder, dev.yanshouwang.camerax.messages.OffsetOrBuilder>(
                corners_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        corners_ = null;
      }
      return cornersBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        dev.yanshouwang.camerax.messages.Barcode, dev.yanshouwang.camerax.messages.Barcode.Builder, dev.yanshouwang.camerax.messages.BarcodeOrBuilder> barcodeBuilder_;
    /**
     * <code>.messages.Barcode barcode = 2;</code>
     * @return Whether the barcode field is set.
     */
    @java.lang.Override
    public boolean hasBarcode() {
      return metadataCase_ == 2;
    }
    /**
     * <code>.messages.Barcode barcode = 2;</code>
     * @return The barcode.
     */
    @java.lang.Override
    public dev.yanshouwang.camerax.messages.Barcode getBarcode() {
      if (barcodeBuilder_ == null) {
        if (metadataCase_ == 2) {
          return (dev.yanshouwang.camerax.messages.Barcode) metadata_;
        }
        return dev.yanshouwang.camerax.messages.Barcode.getDefaultInstance();
      } else {
        if (metadataCase_ == 2) {
          return barcodeBuilder_.getMessage();
        }
        return dev.yanshouwang.camerax.messages.Barcode.getDefaultInstance();
      }
    }
    /**
     * <code>.messages.Barcode barcode = 2;</code>
     */
    public Builder setBarcode(dev.yanshouwang.camerax.messages.Barcode value) {
      if (barcodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        barcodeBuilder_.setMessage(value);
      }
      metadataCase_ = 2;
      return this;
    }
    /**
     * <code>.messages.Barcode barcode = 2;</code>
     */
    public Builder setBarcode(
        dev.yanshouwang.camerax.messages.Barcode.Builder builderForValue) {
      if (barcodeBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        barcodeBuilder_.setMessage(builderForValue.build());
      }
      metadataCase_ = 2;
      return this;
    }
    /**
     * <code>.messages.Barcode barcode = 2;</code>
     */
    public Builder mergeBarcode(dev.yanshouwang.camerax.messages.Barcode value) {
      if (barcodeBuilder_ == null) {
        if (metadataCase_ == 2 &&
            metadata_ != dev.yanshouwang.camerax.messages.Barcode.getDefaultInstance()) {
          metadata_ = dev.yanshouwang.camerax.messages.Barcode.newBuilder((dev.yanshouwang.camerax.messages.Barcode) metadata_)
              .mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        if (metadataCase_ == 2) {
          barcodeBuilder_.mergeFrom(value);
        } else {
          barcodeBuilder_.setMessage(value);
        }
      }
      metadataCase_ = 2;
      return this;
    }
    /**
     * <code>.messages.Barcode barcode = 2;</code>
     */
    public Builder clearBarcode() {
      if (barcodeBuilder_ == null) {
        if (metadataCase_ == 2) {
          metadataCase_ = 0;
          metadata_ = null;
          onChanged();
        }
      } else {
        if (metadataCase_ == 2) {
          metadataCase_ = 0;
          metadata_ = null;
        }
        barcodeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.messages.Barcode barcode = 2;</code>
     */
    public dev.yanshouwang.camerax.messages.Barcode.Builder getBarcodeBuilder() {
      return getBarcodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.messages.Barcode barcode = 2;</code>
     */
    @java.lang.Override
    public dev.yanshouwang.camerax.messages.BarcodeOrBuilder getBarcodeOrBuilder() {
      if ((metadataCase_ == 2) && (barcodeBuilder_ != null)) {
        return barcodeBuilder_.getMessageOrBuilder();
      } else {
        if (metadataCase_ == 2) {
          return (dev.yanshouwang.camerax.messages.Barcode) metadata_;
        }
        return dev.yanshouwang.camerax.messages.Barcode.getDefaultInstance();
      }
    }
    /**
     * <code>.messages.Barcode barcode = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.yanshouwang.camerax.messages.Barcode, dev.yanshouwang.camerax.messages.Barcode.Builder, dev.yanshouwang.camerax.messages.BarcodeOrBuilder> 
        getBarcodeFieldBuilder() {
      if (barcodeBuilder_ == null) {
        if (!(metadataCase_ == 2)) {
          metadata_ = dev.yanshouwang.camerax.messages.Barcode.getDefaultInstance();
        }
        barcodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.yanshouwang.camerax.messages.Barcode, dev.yanshouwang.camerax.messages.Barcode.Builder, dev.yanshouwang.camerax.messages.BarcodeOrBuilder>(
                (dev.yanshouwang.camerax.messages.Barcode) metadata_,
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      metadataCase_ = 2;
      onChanged();;
      return barcodeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:messages.MLMetadata)
  }

  // @@protoc_insertion_point(class_scope:messages.MLMetadata)
  private static final dev.yanshouwang.camerax.messages.MLMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.yanshouwang.camerax.messages.MLMetadata();
  }

  public static dev.yanshouwang.camerax.messages.MLMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MLMetadata>
      PARSER = new com.google.protobuf.AbstractParser<MLMetadata>() {
    @java.lang.Override
    public MLMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MLMetadata(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MLMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MLMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.yanshouwang.camerax.messages.MLMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

