// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax.messages;

public interface PreviewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.Preview)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string viewId = 1;</code>
   * @return The viewId.
   */
  java.lang.String getViewId();
  /**
   * <code>string viewId = 1;</code>
   * @return The bytes for viewId.
   */
  com.google.protobuf.ByteString
      getViewIdBytes();
}
