name: camerax
description: A camera plugin for flutter, which use CameraX on Android, native API on iOS, supports preview, image & ML analysis, image capture and video capture.
version: 0.2.0
homepage: "https://github.com/yanshouwang/camerax"

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  camerax_core:
    path: ../camerax_core
  camerax_android:
    path: ../camerax_android
  camerax_ios:
    path: ../camerax_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: camerax_android
      ios:
        default_package: camerax_ios
