-keep class androidx.camera.core.** { *; }
-keep class androidx.camera.view.** { *; }
-keep class androidx.camera.mlkit.vision.** { *; }
-keep class androidx.lifecycle.** { *; }
-keep class com.google.common.util.concurrent.** { *; }