-keep class androidx.camera.core.** { *; }
-keep class androidx.camera.video.** { *; }
-keep class androidx.camera.view.** { *; }
-keep class androidx.camera.mlkit.vision.** { *; }
-keep class androidx.lifecycle.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.google.common.** { *; }
-keep class com.google.mlkit.vision.** { *; }