name: camerax_ios
description: "iOS implementation of the camerax plugin."
version: 0.0.1
homepage: https://github.com/yanshouwang/camerax
repository: https://github.com/yanshouwang/camerax
issue_tracker: https://github.com/yanshouwang/camerax/issues
topics:
  - camera
  - camerax

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camerax_platform_interface:
    path: ../camerax_platform_interface
  logging: ^1.2.0
  hybrid_logging: ^1.0.0
  ffi: ^2.1.2
  objective_c: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^13.0.0

flutter:
  plugin:
    implements: camerax
    platforms:
      ios:
        pluginClass: CameraXiOSPlugin
        dartPluginClass: CameraXiOSPlugin
