name: camerax_ios
description: "iOS implementation of the camerax plugin."
version: 1.0.0-dev.9
repository: https://github.com/yanshouwang/camerax
issue_tracker: https://github.com/yanshouwang/camerax/issues
topics:
  - camera
  - camerax

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  camerax_platform_interface: ^1.0.0-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.3.2

flutter:
  plugin:
    implements: camerax
    platforms:
      ios:
        pluginClass: CameraXiOSPlugin
        dartPluginClass: CameraXiOSPlugin
