//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax.messages;

@kotlin.jvm.JvmName("-initializemLMetadataObject")
inline fun mLMetadataObject(block: dev.yanshouwang.camerax.messages.MLMetadataObjectKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.messages.MLMetadataObject =
  dev.yanshouwang.camerax.messages.MLMetadataObjectKt.Dsl._create(dev.yanshouwang.camerax.messages.MLMetadataObject.newBuilder()).apply { block() }._build()
object MLMetadataObjectKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: dev.yanshouwang.camerax.messages.MLMetadataObject.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.messages.MLMetadataObject.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.messages.MLMetadataObject = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class BarcodesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .messages.Barcode barcodes = 1;</code>
     */
     val barcodes: com.google.protobuf.kotlin.DslList<dev.yanshouwang.camerax.messages.Barcode, BarcodesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getBarcodesList()
      )
    /**
     * <code>repeated .messages.Barcode barcodes = 1;</code>
     * @param value The barcodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addBarcodes")
    fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.camerax.messages.Barcode, BarcodesProxy>.add(value: dev.yanshouwang.camerax.messages.Barcode) {
      _builder.addBarcodes(value)
    }
    /**
     * <code>repeated .messages.Barcode barcodes = 1;</code>
     * @param value The barcodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignBarcodes")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.camerax.messages.Barcode, BarcodesProxy>.plusAssign(value: dev.yanshouwang.camerax.messages.Barcode) {
      add(value)
    }
    /**
     * <code>repeated .messages.Barcode barcodes = 1;</code>
     * @param values The barcodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllBarcodes")
    fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.camerax.messages.Barcode, BarcodesProxy>.addAll(values: kotlin.collections.Iterable<dev.yanshouwang.camerax.messages.Barcode>) {
      _builder.addAllBarcodes(values)
    }
    /**
     * <code>repeated .messages.Barcode barcodes = 1;</code>
     * @param values The barcodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllBarcodes")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.camerax.messages.Barcode, BarcodesProxy>.plusAssign(values: kotlin.collections.Iterable<dev.yanshouwang.camerax.messages.Barcode>) {
      addAll(values)
    }
    /**
     * <code>repeated .messages.Barcode barcodes = 1;</code>
     * @param index The index to set the value at.
     * @param value The barcodes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setBarcodes")
    operator fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.camerax.messages.Barcode, BarcodesProxy>.set(index: kotlin.Int, value: dev.yanshouwang.camerax.messages.Barcode) {
      _builder.setBarcodes(index, value)
    }
    /**
     * <code>repeated .messages.Barcode barcodes = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearBarcodes")
    fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.camerax.messages.Barcode, BarcodesProxy>.clear() {
      _builder.clearBarcodes()
    }

  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.messages.MLMetadataObject.copy(block: dev.yanshouwang.camerax.messages.MLMetadataObjectKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.messages.MLMetadataObject =
  dev.yanshouwang.camerax.messages.MLMetadataObjectKt.Dsl._create(this.toBuilder()).apply { block() }._build()

